# PROPRIEDADES GERAIS

# Redireciona o local do arquivo. O nome do arquivo pode ser alterado
spring.banner.location: classpath:/other/banner.txt
logging.config: classpath:other/logback-spring.xml

# PROPRIEDADES IMPORTADAS
spring.config.import:
  - "classpath:properties/app-prop.yml"
  - "classpath:properties/database-prop.yml"
  - "classpath:properties/actuator-prop.yml"
  - "classpath:properties/banner-prop.yml"
  - "classpath:properties/cache-prop.yml"
  - "classpath:properties/swagger-prop.yml"
  - "classpath:properties/kafka-prop.yml"



