openapi: 3.0.0
info:
  version: 1.0.0
  title: API de Produtos
  #  title: PEGASUS-SA → API de Produtos
  termsOfService: http://localhost:8080/terms
  description: |
    API RESTful CRUD de controle de produtos para estudo.  
    
    #### 🍵🍵🍵 NOTAS DO DESENVOLVEDOR 🍵🍵🍵    
    
    ##### Metricas
    - Todas as métricas disponíveis: `http://localhost:8080/actuator/metrics`
    - Métrica customizada de contagem de requests: `http://localhost:8080/actuator/metrics/http_requests_total`
    - Métrica customizada de duração de requests: `http://localhost:8080/actuator/metrics/http_request_duration_ms`
    - Formato Prometheus (todas as métricas): ` http://localhost:8080/actuator/prometheus`
    
    ##### DataBase `http://localhost:8080/h2-console`
    - Driver class: `ver application.yaml` → `spring.datasource.driver-class-name`
    - JDBC URL: `ver application.yaml` → `spring.datasource.url`
    - User Name: `ver application.yaml` → `spring.datasource.username`
    - Password: `ver application.yaml` → `spring.datasource.password`


  contact:
    name: Enterprise
    email: suporte@pegasus.com.br
    url: http://localhost:8080
  license:
    name: License
    url: http://localhost:8080/license

servers:
  - url: http://localhost:8080
    description: Servidor local para solicitações de produtos

tags:
  - { name: product, description: produto }

paths:

  /product:
    parameters:
      - $ref: '#/components/parameters/_header_x_trace_id'

    get:
      tags: [ product ]
      operationId: find-all-product
      parameters:
        - $ref: '#/components/parameters/_query_page'
        - $ref: '#/components/parameters/_query_size'
      summary: Busca uma paginação de elementos
      responses:
        '200':
          description: Retorna a paginação solicitada
          content:
            application/json:
              schema: { $ref: '#/components/schemas/product-page-response-type' }
        "400": { $ref: '#/components/responses/bad-request-response' }
        "500": { $ref: '#/components/responses/internal-server-error-response' }

    post:
      tags: [ product ]
      operationId: create-product
      summary: Cria um novo elemento
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/product-create-body-type' }
      responses:
        '201':
          description: Retorna o elemento criado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/product-type' }
        "400": { $ref: '#/components/responses/bad-request-response' }
        "409": { $ref: '#/components/responses/conflict-response' }
        "500": { $ref: '#/components/responses/internal-server-error-response' }

  /product/{id}:
    parameters:
      - $ref: '#/components/parameters/_header_x_trace_id'
      - $ref: '#/components/parameters/_path_id'

    get:
      tags: [ product ]
      operationId: find-by-id-product
      summary: Busca um elemento pelo ID
      responses:
        '200':
          description: O elemento correspondente ao ID
          content:
            application/json:
              schema: { $ref: '#/components/schemas/product-type' }
        "404": { $ref: '#/components/responses/not-found-response' }
        "500": { $ref: '#/components/responses/internal-server-error-response' }

    put:
      tags: [ product ]
      operationId: update-product
      summary: Atualiza um elemento pelo ID (por completo)
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/product-update-body-type' }
      responses:
        '200': { description: ok }
        "400": { $ref: '#/components/responses/bad-request-response' }
        "404": { $ref: '#/components/responses/not-found-response' }
        "409": { $ref: '#/components/responses/conflict-response' }
        "500": { $ref: '#/components/responses/internal-server-error-response' }

    delete:
      tags: [ product ]
      operationId: delete-product
      summary: Deleta um elemento pelo ID
      responses:
        '204': { description: ok }
        "404": { $ref: '#/components/responses/not-found-response' }
        "500": { $ref: '#/components/responses/internal-server-error-response' }

components:
  schemas:
    att-trace-id: { type: string, format: uuid, example: a12f3cde-45b6-7890-abc1-def234567890 }

    att-ex-status: { type: integer, format: int32, example: 400, description: código do erro padrão HTTP }
    att-ex-error: { type: string, example: Bad Request, description: Nome do erro padrão HTTP }
    att-ex-message: { type: string, example: Validation error, description: Motivo do problema }
    att-ex-timestamp: { type: string, format: date-time, example: 2025-11-01T12:34:56Z, description: DMomento do problema }
    att-ex-path: { type: string, example: "/product", description: Endpoint que causou o erro }

    att-page: { type: integer, example: 0, default: 0, description: Página atual (0-based) }
    att-size: { type: integer, example: 10, default: 10, description: Quantidade de elementos por página }
    att-elements: { type: integer, format: int64, example: 300, description: Quantidade de elementos retornados na página }
    att-pages: { type: integer, example: 10, description: Quantidade de páginas disponíveis }
    att-previous: { type: boolean, example: true, description: Verificação de existência de página anterior }
    att-next: { type: boolean, example: true, description: Verificação de existência de página posterior }

    att-id: { type: integer, format: int64, example: 9876543210, description: Identificador do produto }
    att-name: { type: string, minLength: 1, example: Chocolate, description: Nome do produto. Obrigatório e não pode ser vazio }
    att-price: { type: number, format: float, minimum: 0, multipleOf: 0.01, example: 3.52, description: Preço do produto. Obrigatório e não pode ser negativo. }
    att-quantity: { type: integer, minimum: 0, example: 10, description: Quantidade do produto. Obrigatório e não pode ser negativo. }
    att-createdAt: { type: string, format: date-time, example: 2025-01-31T10:15:30Z, description: Data/Hora em que o registro foi criado. }
    att-updatedAt: { type: string, format: date-time, example: 2025-01-31T10:15:30Z, description: Data/Hora em que o registro foi modificado pela última vez. }

    product-type:
      type: object
      properties:
        id: { $ref: '#/components/schemas/att-id' }
        name: { $ref: '#/components/schemas/att-name' }
        price: { $ref: '#/components/schemas/att-price' }
        quantity: { $ref: '#/components/schemas/att-quantity' }
        createdAt: { $ref: '#/components/schemas/att-createdAt' }
        updatedAt: { $ref: '#/components/schemas/att-updatedAt' }

    product-page-response-type:
      type: object
      properties:
        pagination: { $ref: '#/components/schemas/pagination-type' }
        data:
          type: array
          items: { $ref: '#/components/schemas/product-type' }

    product-create-body-type:
      type: object
      required: [ name, price, quantity ]
      properties:
        name: { $ref: '#/components/schemas/att-name' }
        price: { $ref: '#/components/schemas/att-price' }
        quantity: { $ref: '#/components/schemas/att-quantity' }

    product-update-body-type:
      type: object
      required: [ name, price, quantity ]
      properties:
        name: { $ref: '#/components/schemas/att-name' }
        price: { $ref: '#/components/schemas/att-price' }
        quantity: { $ref: '#/components/schemas/att-quantity' }

    pagination-type:
      type: object
      properties:
        page: { $ref: '#/components/schemas/att-page' }
        size: { $ref: '#/components/schemas/att-size' }
        elements: { $ref: '#/components/schemas/att-elements' }
        pages: { $ref: '#/components/schemas/att-pages' }
        previous: { $ref: '#/components/schemas/att-previous' }
        next: { $ref: '#/components/schemas/att-next' }

    exception-response-type:
      type: object
      description: Estrutura padrão de erro da API
      required: [ status, error, message ]
      properties:
        traceId: { $ref: '#/components/schemas/att-trace-id' }
        status: { $ref: '#/components/schemas/att-ex-status' }
        error: { $ref: '#/components/schemas/att-ex-error' }
        message: { $ref: '#/components/schemas/att-ex-message' }
        timestamp: { $ref: '#/components/schemas/att-ex-timestamp' }
        path: { $ref: '#/components/schemas/att-ex-path' }

  responses:

    bad-request-response:
      description: Requisição inválida
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception-response-type'
          example:
            - code: 400
              message: Bad Request
              messageDetail: Invalid Parameter X

    not-found-response:
      description: Recurso não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception-response-type'
          example:
            - code: 404
              message: Not Found
              messageDetail: Element not found

    conflict-response:
      description: Elemento já Cadastrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception-response-type'
          example:
            - code: 409
              message: Conflict
              messageDetail: Element already registered

    internal-server-error-response:
      description: Erro interno no servidor
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception-response-type'
          example:
            - { code: 500, message: Internal Server Error, messageDetail: PROBLEMS IN QUERYING THE DATABASE }

  parameters:
    _header_x_trace_id:
      name: X-Trace-Id
      in: header
      description: Id da requisição
      required: true
      schema: { $ref: '#/components/schemas/att-trace-id' }

    _path_id:
      description: Identificador do item. `id > 0`
      in: path
      name: id
      required: true
      schema: { $ref: '#/components/schemas/att-id' }

    _query_page:
      description: >
        Página atual (0-based) `page >= 0`
      in: query
      name: page
      schema: { $ref: '#/components/schemas/att-page' }

    _query_size:
      description: >
        Quantidade de itens  da paginação `size > 0`
      in: query
      name: size
      schema: { $ref: '#/components/schemas/att-size' }
