DROP TABLE IF EXISTS TB_PRODUCT;

--CREATE TABLE TB_PRODUCT (
CREATE TABLE IF NOT EXISTS TB_PRODUCT (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(150) NOT NULL,
  PRICE DECIMAL(15, 2) NOT NULL,
  QUANTITY INT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP
);
